#! python
# January 21, 2018


def find_element_by_atomic_number(number: int):
    for _symbol in TABLE:
        if TABLE[_symbol]['atomic number'] == number:
            found = TABLE[_symbol]
            found['symbol'] = _symbol
            return found


def find_element(what: str):
    """
    Example: Ne, not ne. Neon and neon can be.
    Returns None if no element is found.
    Returns a Dictionary if an element is found.
    """
    if what in TABLE:
        _e = TABLE[what]
        _e['symbol'] = what[0].upper() + what[1:]
        return _e
    else:
        for symbol in TABLE:
            if what.lower() in TABLE[symbol]['name'].lower():
                _e = TABLE[symbol]
                _e['symbol'] = symbol
                return _e


TABLE = {
    'H': {
        'name': 'Hydrogen',
        'atomic number': 1,
        'electronic configuration': '1s^1',
        'atomic weight': (1.0078, 1.0081),
        'oxidation state': '+1, -1',
        'melting point': -259.14,
        'boiling point': -252.87,
        'density': 0.089,
        'electronegativity': 2.1,
        'classification': ('gas', 'primordial'),
        'group': 'Non-Metals'
    },
    'C': {
        'name': 'Carbon',
        'atomic number': 6,
        'electronic configuration': '1s^2 2s^2 2p^2',
        'atomic weight': (12.01, 12.012),
        'oxidation state': '+2, +4',
        'melting point': 3550,
        'boiling point': 4827,
        'density': 3.52,
        'electronegativity': 2.5,
        'classification': ('solid', 'primordial'),
        'group': 'Non-Metals'
    },
    'N': {
        'name': 'Nitrogen',
        'atomic number': 7,
        'electronic configuration': '1s^2 2s^2 2p^3',
        'atomic weight': (),
        'oxidation state': f'{chr(177)}1{chr(177)}2{chr(177)}3, +4, +5',
        'melting point': -209.9,
        'boiling point': -195.8,
        'density': 1.25,
        'electronegativity': 3.0,
        'classification': ('gas', 'primordial'),
        'group': 'Non-Metals'
    },
    'O': {
        'name': 'Oxygen',
        'atomic number': 8,
        'electronic configuration': '1s^2 2s^2 2p^4',
        'atomic weight': (15.999, 16.00),
        'oxidation state': '-2',
        'melting point': -218.4,
        'boiling point': -182.9,
        'density': 1.429,
        'electronegativity': 3.5,
        'classification': ('gas', 'primordial'),
        'group': 'Non-Metals'
    },
    'P': {
        'name': 'Phosphorus',
        'atomic number': 15,
        'electronic configuration': '(N2) 3s^2 3p^4',
        'atomic weight': 30.974,
        'oxidation state': f'{chr(177)}3, 5',
        'melting point': 44.1,
        'boiling point': 280,
        'density': 1.83,
        'electronegativity': 2.1,
        'classification': ('solid', 'primordial'),
        'group': 'Non-Metals'
    },
    'S': {
        'name': 'Sulfur',
        'atomic number': 16,
        'electronic configuration': '(Ne) 3s^2 3p^4',
        'atomic weight': (32.06, 32.08),
        'oxidation state': '-2, +4, 6',
        'melting point': 112.8,
        'boiling point': 444.6,
        'density': 2.07,
        'electronegativity': 2.5,
        'classification': ('solid', 'primordial'),
        'group': 'Non-Metals'
    },
    'Se': {
        'name': 'Selenium',
        'atomic number': 16,
        'electronic configuration': '(Ar) 3d^10 4s^2 4p^4',
        'atomic weight': 78.96,
        'oxidation state': '-2, +4, 6',
        'melting point': 217,
        'boiling point': 685,
        'density': 4.82,
        'electronegativity': 2.4,
        'classification': ('solid', 'primordial'),
        'group': 'Non-Metals'
    },
    'Be': {
        'name': 'Beryllium',
        'atomic number': 4,
        'electronic configuration': '1s^2 2s^2',
        'atomic weight': 9.012,
        'oxidation state': '+2',
        'melting point': 1278,
        'boiling point': 1290,
        'density': 1.85,
        'electronegativity': 1.5,
        'classification': ('solid', 'primordial'),
        'group': 'Alkaline Earth Metals'
    },
    'Mg': {
        'name': 'Magnesium',
        'atomic number': 12,
        'electronic configuration': '(Ne) 3s^2',
        'atomic weight': 24.305,
        'oxidation state': '+2',
        'melting point': 649,
        'boiling point': 1090,
        'density': 1.74,
        'electronegativity': 1.2,
        'classification': ('solid', 'primordial'),
        'group': 'Alkaline Earth Metals'
    },
    'Ca': {
        'name': 'Calcium',
        'atomic number': 20,
        'electronic configuration': '(Ar) 4s^2',
        'atomic weight': 40.078,
        'oxidation state': '+2',
        'melting point': 839,
        'boiling point': 1484,
        'density': 1.55,
        'electronegativity': 1.0,
        'classification': ('solid', 'primordial'),
        'group': 'Alkaline Earth Metals'
    },
    'Sr': {
        'name': 'Strontium',
        'atomic number': 38,
        'electronic configuration': '(Kr) 5s^2',
        'atomic weight': 87.62,
        'oxidation state': '+2',
        'melting point': 769,
        'boiling point': 1384,
        'density': 2.6,
        'electronegativity': 1.0,
        'classification': ('solid', 'primordial'),
        'group': 'Alkaline Earth Metals'
    },
    'Ba': {
        'name': 'Barium',
        'atomic number': 56,
        'electronic configuration': '(Xe) 6s^2',
        'atomic weight': 137.327,
        'oxidation state': '+2',
        'melting point': 725,
        'boiling point': 1640,
        'density': 3.5,
        'electronegativity': 0.9,
        'classification': ('solid', 'primordial'),
        'group': 'Alkaline Earth Metals'
    },
    'Ra': {
        'name': 'Radium',
        'atomic number': 88,
        'electronic configuration': '(Rn) 7s^2',
        'atomic weight': 226,
        'oxidation state': '+2',
        'melting point': 700,
        'boiling point': 1140,
        'density': 5,
        'electronegativity': 0.9,
        'classification': ('solid', 'rise naturally from decay'),
        'group': 'Alkaline Earth Metals'
    },
    'B': {
            'name': 'Boron',
            'atomic number': 5,
            'electronic configuration': '1s^2 2s^2 2p^1',
            'atomic weight': (10.81, 10.82),
            'oxidation state': '+3',
            'melting point': 2300,
            'boiling point': 2550,
            'density': 2.35,
            'electronegativity': 2.0,
            'classification': ('solid', 'primordial'),
            'group': 'Metalloids/Semi-metals'
        },
    'Si': {
        'name': 'Silicon',
        'atomic number': 14,
        'electronic configuration': '(Ne) 3s^2 3p^2',
        'atomic weight': (28.084, 28.086),
        'oxidation state': f'+2, {chr(177)}4',
        'melting point': 1410,
        'boiling point': 2355,
        'density': 2.24,
        'electronegativity': 1.8,
        'classification': ('solid', 'primordial'),
        'group': 'Metalloids/Semi-metals'
    },
    'Ge': {
        'name': 'Germanium',
        'atomic number': 32,
        'electronic configuration': '(Ar) 3d^10 4s^2 4p^2',
        'atomic weight': 72.63,
        'oxidation state': '+2, 4',
        'melting point': 937.4,
        'boiling point': 2830,
        'density': 5.36,
        'electronegativity': 1.8,
        'classification': ('solid', 'primordial'),
        'group': 'Metalloids/Semi-metals'
    },
    'As': {
        'name': 'Arsenic',
        'atomic number': 33,
        'electronic configuration': '(Ar) 3d^10 4s^2 4p^3',
        'atomic weight': 74.922,
        'oxidation state': f'{chr(177)}3, 5',
        'melting point': 817,
        'boiling point': 613,
        'density': 5.72,
        'electronegativity': 2.0,
        'classification': ('solid', 'primordial'),
        'group': 'Metalloids/Semi-metals'
    },
    'Sb': {
        'name': 'Antimony',
        'atomic number': 51,
        'electronic configuration': '(Kr) 4d^10 5s^2 5p^3',
        'atomic weight': 121.760,
        'oxidation state': '+3, 5',
        'melting point': 630.7,
        'boiling point': 1750,
        'density': 6.62,
        'electronegativity': 1.9,
        'classification': ('solid', 'primordial'),
        'group': 'Metalloids/Semi-metals'
    },
    'Te': {
        'name': 'Tellurium',
        'atomic number': 52,
        'electronic configuration': '(Kr) 4d^10 5s^2 5p^4',
        'atomic weight': 127.60,
        'oxidation state': '-2, +4, 6',
        'melting point': 449.5,
        'boiling point': 989.8,
        'density': 6.24,
        'electronegativity': 2.1,
        'classification': ('solid', 'primordial'),
        'group': 'Metalloids/Semi-metals'
    },
    'Po': {
        'name': 'Polonium',
        'atomic number': 84,
        'electronic configuration': '(Xe) 4f^14 5d^10 6s^2 6p^4',
        'atomic weight': 209,
        'oxidation state': '+2, 4',
        'melting point': 254,
        'boiling point': 962,
        'density': 9.4,
        'electronegativity': 2.0,
        'classification': ('solid', 'radio active'),
        'group': 'Metalloids/Semi-metals'
    },
    'He': {
        'name': 'Helium',
        'atomic number': 2,
        'electronic configuration': '1s^2',
        'atomic weight': 4.00260,
        'oxidation state': '0',
        'melting point': -272.2,
        'boiling point': 268.9,
        'density': 0.124,
        'electronegativity': None,
        'classification': ('gas', 'primordial'),
        'group': 'Noble Gas'
    },
    'Ne': {
        'name': 'Neon',
        'atomic number': 10,
        'electronic configuration': '1s^2 2s^2 2p^6',
        'atomic weight': 20.18,
        'oxidation state': '-248.7',
        'melting point': 246.0,
        'boiling point': 1.204,
        'density': 0,
        'electronegativity': None,
        'classification': ('gas', 'primordial'),
        'group': 'Noble Gas'
    },
    'Ar': {
        'name': 'Argon',
        'atomic number': 18,
        'electronic configuration': '(Ne) 3s^2 3p^6',
        'atomic weight': 39.948,
        'oxidation state': '0',
        'melting point': -189.2,
        'boiling point': -185.7,
        'density': 1.65,
        'electronegativity': None,
        'classification': ('gas', 'primordial'),
        'group': 'Noble Gas'
    },
    'Kr': {
        'name': 'Krypton',
        'atomic number': 36,
        'electronic configuration': '(Ar) 3d^10 4s^2 4p^6',
        'atomic weight': 83.798,
        'oxidation state': '0',
        'melting point': -156.6,
        'boiling point': -152.3,
        'density': 3.4,
        'electronegativity': None,
        'classification': ('gas', 'primordial'),
        'group': 'Noble Gas'
    },
    'Xe': {
        'name': 'Xenon',
        'atomic number': 54,
        'electronic configuration': '(Kr) 4d^10 5s^2 5p^6',
        'atomic weight': 131.293,
        'oxidation state': '0',
        'melting point': -112,
        'boiling point': -107,
        'density': 3.05,
        'electronegativity': None,
        'classification': ('gas', 'primordial'),
        'group': 'Noble Gas'
    },
    'Rn': {
        'name': 'Radon',
        'atomic number': 86,
        'electronic configuration': '(Xe) 4f^14 5d^10 6s^2 6p^6',
        'atomic weight': 222,
        'oxidation state': '0',
        'melting point': -71,
        'boiling point': -61.8,
        'density': 9.72,
        'electronegativity': None,
        'classification': ('gas', 'rise naturally from decay'),
        'group': 'Noble Gas'
    },
    'Og': {
        'name': 'Oganesson',
        'atomic number': 118,
        'electronic configuration': '(Rn) 5f^14 6d^10 7s^2 7p^6',
        'atomic weight': 0,
        'oxidation state': '0',
        'melting point': 0,
        'boiling point': 0,
        'density': 0,
        'electronegativity': None,
        'classification': ('gas', 'synthetic', 'radio active'),
        'group': 'Noble Gas'
    },
    'F': {
        'name': 'Fluorine',
        'atomic number': 9,
        'electronic configuration': '1s^2 2s^2 2p^5',
        'atomic weight': 18.998,
        'oxidation state': '-1',
        'melting point': -219.62,
        'boiling point': -188.14,
        'density': 1.696,
        'electronegativity': 4.0,
        'classification': ('gas', 'primordial'),
        'group': 'Halogens'
    },
    'Cl': {
        'name': 'Chlorine',
        'atomic number': 17,
        'electronic configuration': '(Ne) 3s^2 3p^5',
        'atomic weight': (35.45, 35.46),
        'oxidation state': f'{chr(177)}1, +5, 7',
        'melting point': -100.9,
        'boiling point': -34.6,
        'density': 3.214,
        'electronegativity': 3.0,
        'classification': ('gas', 'primordial'),
        'group': 'Halogens'
    },
    'Br': {
        'name': 'Bromine',
        'atomic number': 35,
        'electronic configuration': '(Ar) 3d^10 4s^2 4p^5',
        'atomic weight': 79.904,
        'oxidation state': f'{chr(177)}1, +5',
        'melting point': -7.2,
        'boiling point': 58.8,
        'density': 3.12,
        'electronegativity': 2.8,
        'classification': ('liquid', 'primordial'),
        'group': 'Halogens'
    },
    'I': {
        'name': 'Iodine',
        'atomic number': 53,
        'electronic configuration': '(Kr) 4d^10 5s^2 5p^5',
        'atomic weight': 126.90447,
        'oxidation state': f'{chr(177)}1, +5, 7',
        'melting point': 113.50,
        'boiling point': 184.35,
        'density': 4.94,
        'electronegativity': 2.5,
        'classification': ('solid', 'primordial'),
        'group': 'Halogens'
    },
    'At': {
        'name': 'Astatine',
        'atomic number': 85,
        'electronic configuration': '(Xe) 4f^14 5d^10 6s^2 6p^5',
        'atomic weight': 210,
        'oxidation state': f'{chr(117)}1',
        'melting point': 302,
        'boiling point': 337,
        'density': None,
        'electronegativity': 2.2,
        'classification': ('solid', 'rise naturally from decay',
                           'radio active'),
        'group': 'Halogens'
        },
    'Ts': {
        'name': 'Tennessine',
        'atomic number': 117,
        'electronic configuration': '(Rn) 5f^14 6d^10 7s^2 7p^5',
        'atomic weight': None,
        'oxidation state': None,
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Halogens'
    },
    'Li': {
        'name': 'Lithium',
        'atomic number': 3,
        'electronic configuration': '1s^2 s^1',
        'atomic weight': (6.938, 6.997),
        'oxidation state': '+1',
        'melting point': 180.5,
        'boiling point': 1342,
        'density': 0.534,
        'electronegativity': 1.0,
        'classification': ('solid', 'primordial'),
        'group': 'Alkali Metals'
    },
    'Na': {
        'name': 'Sodium',
        'atomic number': 11,
        'electronic configuration': '(Ne) 3s^1',
        'atomic weight': 22.990,
        'oxidation state': '+1',
        'melting point': 97.81,
        'boiling point': 882.9,
        'density': 0.972,
        'electronegativity': 0.9,
        'classification': ('solid', 'primordial'),
        'group': 'Alkali Metals'
    },
    'K': {
        'name': 'Potassium',
        'atomic number': 19,
        'electronic configuration': '(Ar) 4s^1',
        'atomic weight': 39.098,
        'oxidation state': '+1',
        'melting point': 63.25,
        'boiling point': 759.9,
        'density': 0.87,
        'electronegativity': 0.8,
        'classification': ('solid', 'primordial'),
        'group': 'Alkali Metals'
    },
    'Rb': {
        'name': 'Rubidium',
        'atomic number': 37,
        'electronic configuration': '(Kr) 5s^1',
        'atomic weight': 85.468,
        'oxidation state': '+1',
        'melting point': 38.9,
        'boiling point': 686,
        'density': 1.53,
        'electronegativity': 0.8,
        'classification': ('solid', 'primordial'),
        'group': 'Alkali Metals'
    },
    'Cs': {
        'name': 'Cesium',
        'atomic number': 55,
        'electronic configuration': '(Xe) 6s^1',
        'atomic weight': 132.905,
        'oxidation state': '+1',
        'melting point': 28.40,
        'boiling point': 669.3,
        'density': 1.87,
        'electronegativity': 0.7,
        'classification': ('liquid', 'primordial'),
        'group': 'Alkali Metals'
    },
    'Fr': {
        'name': 'Francium',
        'atomic number': 87,
        'electronic configuration': '(Rn) 7s^1',
        'atomic weight': 223,
        'oxidation state': '+1',
        'melting point': 27,
        'boiling point': 677,
        'density': 2.4,
        'electronegativity': 0.7,
        'classification': ('liquid', 'rise naturally from decay'),
        'group': 'Alkali Metals'
    },
    'Sc': {
        'name': 'Scandium',
        'atomic number': 21,
        'electronic configuration': '(Ar) 3d^1 4s^2',
        'atomic weight': 44.956,
        'oxidation state': '+3',
        'melting point': 1539,
        'boiling point': 2832,
        'density': 2.98,
        'electronegativity': 1.3,
        'classification': ('solid', 'primordial'),
        'group': 'Early Transition Metals'
    },
    'Ti': {
        'name': 'Titanium',
        'atomic number': 22,
        'electronic configuration': '(Ar) 3d^2 4s^2',
        'atomic weight': 47.867,
        'oxidation state': '+2, 3, 4',
        'melting point': 1660,
        'boiling point': 3287,
        'density': 4.51,
        'electronegativity': 1.5,
        'classification': ('solid', 'primordial'),
        'group': 'Early Transition Metals'
    },
    'V': {
        'name': 'Vanadium',
        'atomic number': 23,
        'electronic configuration': '(Ar) 3d^3 4s^2',
        'atomic weight': 50.941,
        'oxidation state': '+2, 3, 4, 5',
        'melting point': 1890,
        'boiling point': 3380,
        'density': 6.10,
        'electronegativity': 1.6,
        'classification': ('solid', 'primordial'),
        'group': 'Early Transition Metals'
    },
    'Cr': {
        'name': 'Chromium',
        'atomic number': 24,
        'electronic configuration': '(Ar) 3d^3 4s^2',
        'atomic weight': 51.996,
        'oxidation state': '+2, 3, 6',
        'melting point': 1857,
        'boiling point': 2672,
        'density': 7.14,
        'electronegativity': 1.6,
        'classification': ('solid', 'primordial'),
        'group': 'Early Transition Metals'
    },
    'Mn': {
        'name': 'Manganese',
        'atomic number': 25,
        'electronic configuration': '(Ar) 3d^5 4s^2',
        'atomic weight': 54.938,
        'oxidation state': '+2, 3, 4, 7',
        'melting point': 1244,
        'boiling point': 1962,
        'density': 7.3,
        'electronegativity': 0,
        'classification': ('solid', 'primordial'),
        'group': 'Early Transition Metals'
    },
    'Y': {
        'name': 'Yttrium',
        'atomic number': 39,
        'electronic configuration': '(Kr) 4d^1 5s^2',
        'atomic weight': 88.906,
        'oxidation state': '+3',
        'melting point': 1523,
        'boiling point': 3337,
        'density': 4.457,
        'electronegativity': 1.3,
        'classification': ('solid', 'primordial'),
        'group': 'Early Transition Metals'
    },
    'Zr': {
        'name': 'Zirconium',
        'atomic number': 40,
        'electronic configuration': '(Kr) 4d^2 5s^2',
        'atomic weight': 91.224,
        'oxidation state': '+4',
        'melting point': 1852,
        'boiling point': 4377,
        'density': 6.44,
        'electronegativity': 1.4,
        'classification': ('solid', 'primordial'),
        'group': 'Early Transition Metals'
    },
    'Nb': {
        'name': 'Niobium',
        'atomic number': 41,
        'electronic configuration': '(Kr) 4d^4 5s^1',
        'atomic weight': 92.906,
        'oxidation state': '+3, 5',
        'melting point': 2468,
        'boiling point': 4742,
        'density': 8.66,
        'electronegativity': 1.6,
        'classification': ('solid', 'primordial'),
        'group': 'Early Transition Metals'
    },
    'Mo': {
        'name': 'Molybdenum',
        'atomic number': 42,
        'electronic configuration': '(Kr) 4d^5 5s^1',
        'atomic weight': 95.96,
        'oxidation state': '+3, 5, 6',
        'melting point': 2617,
        'boiling point': 4612,
        'density': 9.01,
        'electronegativity': 1.8,
        'classification': ('solid', 'primordial'),
        'group': 'Early Transition Metals'
    },
    'Tc': {
        'name': 'Technetium',
        'atomic number': 43,
        'electronic configuration': '(Kr) 4d^5 5s^2',
        'atomic weight': 98,
        'oxidation state': '+4, 6, 7',
        'melting point': 2172,
        'boiling point': 4877,
        'density': None,
        'electronegativity': 1.9,
        'classification': ('solid', 'primordial'),
        'group': 'Early Transition Metals'
    },
    'Hf': {
        'name': 'Hafnium',
        'atomic number': 72,
        'electronic configuration': '(Xe) 4f^14 5d^2 6s^2',
        'atomic weight': 178.49,
        'oxidation state': '+4',
        'melting point': 2227,
        'boiling point': 4602,
        'density': 13.1,
        'electronegativity': 1.3,
        'classification': ('solid', 'primordial'),
        'group': 'Early Transition Metals'
    },
    'Ta': {
        'name': 'Tantalum',
        'atomic number': 73,
        'electronic configuration': '(Xe) 4f^14 5d^3 6s^2',
        'atomic weight': 180.948,
        'oxidation state': '+5',
        'melting point': 2996,
        'boiling point': 5425,
        'density': 16.63,
        'electronegativity': 1.5,
        'classification': ('solid', 'primordial'),
        'group': 'Early Transition Metals'
    },
    'W': {
        'name': 'Tungsten',
        'atomic number': 74,
        'electronic configuration': '(Xe) 4f^14 5d^4 6s^2',
        'atomic weight': 183.84,
        'oxidation state': '+6',
        'melting point': 3410,
        'boiling point': 5660,
        'density': 19.3,
        'electronegativity': 1.7,
        'classification': ('solid', 'primordial'),
        'group': 'Early Transition Metals'
    },
    'Re': {
        'name': 'Rhenium',
        'atomic number': 75,
        'electronic configuration': '(Xe) 4f^14 5d^5 6s^2',
        'atomic weight': 186.207,
        'oxidation state': '-1, 6, 7',
        'melting point': 3180,
        'boiling point': 5627,
        'density': 21.04,
        'electronegativity': 1.9,
        'classification': ('solid', 'primordial'),
        'group': 'Early Transition Metals'
    },
    'Rf': {
        'name': 'Rutherfordium',
        'atomic number': 104,
        'electronic configuration': '(Rn) 5f^14 6d^2 7s^2',
        'atomic weight': 265,
        'oxidation state': '+4',
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Early Transition Metals'
    },
    'Db': {
        'name': 'Dubnium',
        'atomic number': 105,
        'electronic configuration': '(Rn) 5f^14 6d^3 7s^2',
        'atomic weight': 268,
        'oxidation state': None,
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Early Transition Metals'
    },
    'Sg': {
        'name': 'Seaborgium',
        'atomic number': 106,
        'electronic configuration': '(Rn) 5f^14 6d^4 7s^2',
        'atomic weight': 271,
        'oxidation state': None,
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Early Transition Metals'
    },
    'Bh': {
        'name': 'Bohrium',
        'atomic number': 107,
        'electronic configuration': '(Rn) 5f^14 6d^5 7s^2',
        'atomic weight': 272,
        'oxidation state': None,
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Early Transition Metals'
    },
    'Fe': {
        'name': 'Iron',
        'atomic number': 26,
        'electronic configuration': '(Ar) 3d^6 4s^2',
        'atomic weight': 55.845,
        'oxidation state': '+2, 3',
        'melting point': 1535,
        'boiling point': 2750,
        'density': 7.87,
        'electronegativity': 1.8,
        'classification': ('solid', 'primordial'),
        'group': 'Late Transition Metals'
    },
    'Co': {
        'name': 'Cobalt',
        'atomic number': 27,
        'electronic configuration': '(Ar) 3d^7 4s^2',
        'atomic weight': 58.933195,
        'oxidation state': '+2, 3',
        'melting point': 1495,
        'boiling point': 2870,
        'density': 8.83,
        'electronegativity': 1.8,
        'classification': ('solid', 'primordial'),
        'group': 'Late Transition Metals'
    },
    'Ni': {
        'name': 'Nickel',
        'atomic number': 28,
        'electronic configuration': '(Ar) 3d^8 4s^2',
        'atomic weight': 58.6934,
        'oxidation state': '+2, 3',
        'melting point': 1453,
        'boiling point': 2732,
        'density': 8.8,
        'electronegativity': 1.8,
        'classification': ('solid', 'primordial'),
        'group': 'Late Transition Metals'
    },
    'Cu': {
        'name': 'Copper',
        'atomic number': 29,
        'electronic configuration': '(Ar) 3d^10 4s^1',
        'atomic weight': 63.546,
        'oxidation state': '+1, 2',
        'melting point': 1083,
        'boiling point': 2567,
        'density': 8.94,
        'electronegativity': 1.9,
        'classification': ('solid', 'primordial'),
        'group': 'Late Transition Metals'
    },
    'Zn': {
        'name': 'Zinc',
        'atomic number': 30,
        'electronic configuration': '(Ar) 3d^10 4s^2',
        'atomic weight': 65.38,
        'oxidation state': '+2',
        'melting point': 419.6,
        'boiling point': 907,
        'density': 7.1,
        'electronegativity': 1.6,
        'classification': ('solid', 'primordial'),
        'group': 'Late Transition Metals'
    },
    'Ru': {
        'name': 'Ruthenium',
        'atomic number': 44,
        'electronic configuration': '(Kr) 4d^7 5s^1',
        'atomic weight': 101.07,
        'oxidation state': '+3, 4, 6, 8',
        'melting point': 2310,
        'boiling point': 3900,
        'density': 12.1,
        'electronegativity': 2.2,
        'classification': ('solid', 'primordial'),
        'group': 'Late Transition Metals'
    },
    'Rh': {
        'name': 'Rhodium',
        'atomic number': 45,
        'electronic configuration': '(Kr) 4d^8 5s^1',
        'atomic weight': 102.9055,
        'oxidation state': '+3, 4',
        'melting point': 1966,
        'boiling point': 3727,
        'density': 12.44,
        'electronegativity': 2.2,
        'classification': ('solid', 'primordial'),
        'group': 'Late Transition Metals'
    },
    'Pd': {
        'name': 'Palladium',
        'atomic number': 46,
        'electronic configuration': '(Kr) 4d^10 5s^0',
        'atomic weight': 106.42,
        'oxidation state': '+2, 4',
        'melting point': 1554,
        'boiling point': 3140,
        'density': 12.16,
        'electronegativity': 2.2,
        'classification': ('solid', 'primordial'),
        'group': 'Late Transition Metals'
    },
    'Ag': {
        'name': 'Silver',
        'atomic number': 47,
        'electronic configuration': '(Kr) 4d^10 5s^1',
        'atomic weight': 107.8682,
        'oxidation state': '+1',
        'melting point': 961.9,
        'boiling point': 2212,
        'density': 10.49,
        'electronegativity': 1.9,
        'classification': ('solid', 'primordial'),
        'group': 'Late Transition Metals'
    },
    'Cd': {
        'name': 'Cadmium',
        'atomic number': 48,
        'electronic configuration': '(Kr) 4d^10 5s^2',
        'atomic weight': 112.411,
        'oxidation state': '+2',
        'melting point': 321,
        'boiling point': 765,
        'density': 8.65,
        'electronegativity': 1.7,
        'classification': ('solid', 'primordial'),
        'group': 'Late Transition Metals'
    },
    'Os': {
        'name': 'Osmium',
        'atomic number': 76,
        'electronic configuration': '(Xe) 4f^14 5d^6 6s^2',
        'atomic weight': 190.23,
        'oxidation state': '+3, 4',
        'melting point': 3045,
        'boiling point': 5027,
        'density': 22.5,
        'electronegativity': 2.2,
        'classification': ('solid', 'primordial'),
        'group': 'Late Transition Metals'
    },
    'Ir': {
        'name': 'Iridium',
        'atomic number': 77,
        'electronic configuration': '(Xe) 4f^14 5d^7 6s^2',
        'atomic weight': 192.217,
        'oxidation state': '+3, 4',
        'melting point': 2410,
        'boiling point': 4130,
        'density': 22.42,
        'electronegativity': 2.2,
        'classification': ('solid', 'primordial'),
        'group': 'Late Transition Metals'
    },
    'Pt': {
        'name': 'Platinum',
        'atomic number': 78,
        'electronic configuration': '(Xe) 4f^14 5d^9 6s^1',
        'atomic weight': 195.084,
        'oxidation state': '+2, 4',
        'melting point': 1772,
        'boiling point': 3827,
        'density': 21.37,
        'electronegativity': 2.2,
        'classification': ('solid', 'primordial'),
        'group': 'Late Transition Metals'
    },
    'Au': {
        'name': 'Gold',
        'atomic number': 79,
        'electronic configuration': '(Xe) 4f^14 5d^10 6s^1',
        'atomic weight': 196.96657,
        'oxidation state': '+1, 3',
        'melting point': 1064,
        'boiling point': 3080,
        'density': 19.32,
        'electronegativity': 2.4,
        'classification': ('solid', 'primordial'),
        'group': 'Late Transition Metals'
    },
    'Hg': {
        'name': 'Mercury',
        'atomic number': 80,
        'electronic configuration': '(Xe) 4f^14 5d^10 6s^2',
        'atomic weight': 200.59,
        'oxidation state': '+1, 2',
        'melting point': 38.87,
        'boiling point': 356.6,
        'density': 13.55,
        'electronegativity': 1.9,
        'classification': ('liquid', 'primordial'),
        'group': 'Late Transition Metals'
    },
    'Hs': {
        'name': 'Hassium',
        'atomic number': 108,
        'electronic configuration': '(Rn) 5f^14 6d^6 7s^2',
        'atomic weight': 270,
        'oxidation state': None,
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Late Transition Metals'
    },
    'Mt': {
        'name': 'Meitnerium',
        'atomic number': 109,
        'electronic configuration': '(Rn) 5f^14 6d^7 7s^2',
        'atomic weight': 276,
        'oxidation state': None,
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Late Transition Metals'
    },
    'Ds': {
        'name': 'Darmstadtium',
        'atomic number': 110,
        'electronic configuration': '(Rn) 5f^14 6d^8 7s^2',
        'atomic weight': 281,
        'oxidation state': None,
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Late Transition Metals'
    },
    'Rg': {
        'name': 'Roentgenium',
        'atomic number': 111,
        'electronic configuration': '(Rn) 5f^14 6d^9 7s^2',
        'atomic weight': 280,
        'oxidation state': None,
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Late Transition Metals'
    },
    'Cn': {
        'name': 'Copernicium',
        'atomic number': 112,
        'electronic configuration': '(Rn) 5f^14 6d^10 7s^2',
        'atomic weight': 285,
        'oxidation state': None,
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('liquid', 'synthetic', 'radio active'),
        'group': 'Late Transition Metals'
    },
    'Al': {
        'name': 'Aluminum',
        'atomic number': 13,
        'electronic configuration': '(Ne) 3s^2 3p^1',
        'atomic weight': 26.982,
        'oxidation state': '+3',
        'melting point': 660,
        'boiling point': 2467,
        'density': 2.70,
        'electronegativity': 1.5,
        'classification': ('solid', 'primordial'),
        'group': 'Basic/Poor Metals'
    },
    'Ga': {
        'name': 'Gallium',
        'atomic number': 31,
        'electronic configuration': '(Ar) 3d^10 4s^2 4p^1',
        'atomic weight': 69.723,
        'oxidation state': '+3',
        'melting point': 29.78,
        'boiling point': 2403,
        'density': 5.9,
        'electronegativity': 1.6,
        'classification': ('liquid', 'primordial'),
        'group': 'Basic/Poor Metals'
    },
    'In': {
        'name': 'Indium',
        'atomic number': 49,
        'electronic configuration': '(Kr) 4d^10 5s^2 5p^1',
        'atomic weight': 114.818,
        'oxidation state': '+3',
        'melting point': 156.6,
        'boiling point': 2080,
        'density': 7.31,
        'electronegativity': 1.7,
        'classification': ('solid', 'primordial'),
        'group': 'Basic/Poor Metals'
    },
    'Sn': {
        'name': 'Tin',
        'atomic number': 50,
        'electronic configuration': '(Kr) 4d^10 5s^2 5p^2',
        'atomic weight': 118.710,
        'oxidation state': '+2, 4',
        'melting point': 232,
        'boiling point': 2270,
        'density': 7.29,
        'electronegativity': 1.8,
        'classification': ('solid', 'primordial'),
        'group': 'Basic/Poor Metals'
    },
    'Tl': {
        'name': 'Thallium',
        'atomic number': 81,
        'electronic configuration': '(Xe) 4f^14 5d^10 6s^2 6p^1',
        'atomic weight': (204.38, 204.39),
        'oxidation state': '+1, 3',
        'melting point': 303.5,
        'boiling point': 1457,
        'density': 11.85,
        'electronegativity': 1.8,
        'classification': ('solid', 'primordial'),
        'group': 'Basic/Poor Metals'
    },
    'Pb': {
        'name': 'Lead',
        'atomic number': 82,
        'electronic configuration': '(Xe) 4f^14 5d^10 6s^2 6p^2',
        'atomic weight': 207.2,
        'oxidation state': '+2, 4',
        'melting point': 327.5,
        'boiling point': 1740,
        'density': 11.4,
        'electronegativity': 1.8,
        'classification': ('solid', 'primordial'),
        'group': 'Basic/Poor Metals'
    },
    'Bi': {
        'name': 'Bismuth',
        'atomic number': 83,
        'electronic configuration': '(Xe) 4f^14 5d^10 6s^2 6p^3',
        'atomic weight': 208.980,
        'oxidation state': '+3, 5',
        'melting point': 271.3,
        'boiling point': 1560,
        'density': 9.78,
        'electronegativity': 1.9,
        'classification': ('solid', 'primordial'),
        'group': 'Basic/Poor Metals'
    },
    'Nh': {
        'name': 'Nihonium',
        'atomic number': 113,
        'electronic configuration': '(Rn) 5f^14 6d^10 7s^2 7p^1',
        'atomic weight': 284,
        'oxidation state': None,
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'primordial'),
        'group': 'Basic/Poor Metals'
    },
    'Fl': {
        'name': 'Flerovium',
        'atomic number': 114,
        'electronic configuration': '(Rn) 5f^14 6d^10 7s^2 7p^2',
        'atomic weight': 289,
        'oxidation state': None,
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Basic/Poor Metals'
    },
    'Mc': {
        'name': 'Moscovium',
        'atomic number': 115,
        'electronic configuration': '(Rn) 5f^14 6d^10 7s^2 p^3',
        'atomic weight': 288,
        'oxidation state': None,
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Basic/Poor Metals'
    },
    'Lv': {
        'name': 'Livermorium',
        'atomic number': 116,
        'electronic configuration': '(Rn) 5f^14 6d^10 7s^2 7p^4',
        'atomic weight': 293,
        'oxidation state': None,
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Basic/Poor Metals'
    },
    'La': {
        'name': 'Lanthanum',
        'atomic number': 57,
        'electronic configuration': '(Xe) 5d^1 6s^2',
        'atomic weight': 138.905,
        'oxidation state': '+3',
        'melting point': 920,
        'boiling point': 3454,
        'density': 6.16,
        'electronegativity': 1.1,
        'classification': ('solid', 'primordial'),
        'group': 'Lanthanides'
    },
    'Ce': {
        'name': 'Cerium',
        'atomic number': 58,
        'electronic configuration': '(Xe) 4f^1 5d^1 6s^2',
        'atomic weight': 140.116,
        'oxidation state': '+3, 4',
        'melting point': 798,
        'boiling point': 3257,
        'density': 6.77,
        'electronegativity': 1.1,
        'classification': ('solid', 'primordial'),
        'group': 'Lanthanides'
    },
    'Pr': {
        'name': 'Praseodymium',
        'atomic number': 59,
        'electronic configuration': '(Xe) 4f^3  5d^0 6s^2',
        'atomic weight': 140.908,
        'oxidation state': '+3',
        'melting point': 931,
        'boiling point': 3212,
        'density': 6.77,
        'electronegativity': 1.1,
        'classification': ('solid', 'primordial'),
        'group': 'Lanthanides'
    },
    'Nd': {
        'name': 'Neodymium',
        'atomic number': 60,
        'electronic configuration': '(Xe) 4f^4 5d^0 6s^2',
        'atomic weight': 144.242,
        'oxidation state': '+3',
        'melting point': 1010,
        'boiling point': 3127,
        'density': 7.00,
        'electronegativity': 1.2,
        'classification': ('solid', 'primordial'),
        'group': 'Lanthanides'
    },
    'Pm': {
        'name': 'Promethium',
        'atomic number': 61,
        'electronic configuration': '(Xe) 4f^5 5d^0 6s^2',
        'atomic weight': 145,
        'oxidation state': '+3',
        'melting point': 1080,
        'boiling point': 2460,
        'density': 7.22,
        'electronegativity': None,
        'classification': ('solid', 'rise naturally from decay'),
        'group': 'Lanthanides'
    },
    'Sm': {
        'name': 'Samarium',
        'atomic number': 62,
        'electronic configuration': '(Xe) 4f^6 5d^0 6s^2',
        'atomic weight': 150.36,
        'oxidation state': '+2, 3',
        'melting point': 1072,
        'boiling point': 1778,
        'density': 7.54,
        'electronegativity': 1.2,
        'classification': ('solid', 'primordial'),
        'group': 'Lanthanides'
    },
    'Eu': {
        'name': 'Europium',
        'atomic number': 63,
        'electronic configuration': '(Xe) 4f^7 5d^0 6s^2',
        'atomic weight': 151.964,
        'oxidation state': '+2, 3',
        'melting point': 822,
        'boiling point': 1597,
        'density': 5.24,
        'electronegativity': None,
        'classification': ('solid', 'primordial'),
        'group': 'Lanthanides'
    },
    'Gd': {
        'name': 'Godalinium',
        'atomic number': 64,
        'electronic configuration': '(Xe) 4f^7 5d^1 6s^2',
        'atomic weight': 157.25,
        'oxidation state': '+3',
        'melting point': 1311,
        'boiling point': 3233,
        'density': 7.89,
        'electronegativity': 1.1,
        'classification': ('solid', 'primordial'),
        'group': 'Lanthanides'
    },
    'Tb': {
        'name': 'Terbium',
        'atomic number': 65,
        'electronic configuration': '(Xe) 4f^9 5d^0 6s^2',
        'atomic weight': 158.92535,
        'oxidation state': '+3',
        'melting point': 1360,
        'boiling point': 3041,
        'density': 8.25,
        'electronegativity': 1.2,
        'classification': ('solid', 'primordial'),
        'group': 'Lanthanides'
    },
    'Dy': {
        'name': 'Dysprosium',
        'atomic number': 66,
        'electronic configuration': '(Xe) 4f^10 5d^0 6s^2',
        'atomic weight': 162.500,
        'oxidation state': '+3',
        'melting point': 1409,
        'boiling point': 2335,
        'density': 8.56,
        'electronegativity': None,
        'classification': ('solid', 'primordial'),
        'group': 'Lanthanides'
    },
    'Ho': {
        'name': 'Holmium',
        'atomic number': 67,
        'electronic configuration': '(Xe) 4f^11 5d^0 6s^2',
        'atomic weight': 164.93032,
        'oxidation state': '+3',
        'melting point': 1470,
        'boiling point': 2720,
        'density': 8.78,
        'electronegativity': 1.2,
        'classification': ('solid', 'primordial'),
        'group': 'Lanthanides'
    },
    'Er': {
        'name': 'Erbium',
        'atomic number': 68,
        'electronic configuration': '(Xe) 4f^12 5d^0 6s^2',
        'atomic weight': 167.259,
        'oxidation state': '+3',
        'melting point': 1522,
        'boiling point': 2510,
        'density': 9.04,
        'electronegativity': 1.2,
        'classification': ('solid', 'primordial'),
        'group': 'Lanthanides'
    },
    'Tm': {
        'name': 'Thulium',
        'atomic number': 69,
        'electronic configuration': '(Xe) 4f^13 5d^0 6s^2',
        'atomic weight': 168.9342,
        'oxidation state': '+3',
        'melting point': 1545,
        'boiling point': 1727,
        'density': 9.32,
        'electronegativity': 1.2,
        'classification': ('solid', 'primordial'),
        'group': 'Lanthanides'
    },
    'Yb': {
        'name': 'Ytterbium',
        'atomic number': 70,
        'electronic configuration': '(Xe) 4f^14 5d^0 6s^2',
        'atomic weight': 173.054,
        'oxidation state': '+2, 3',
        'melting point': 824,
        'boiling point': 1193,
        'density': 6.97,
        'electronegativity': 1.1,
        'classification': ('solid', 'primordial'),
        'group': 'Lanthanides'
    },
    'Lu': {
        'name': 'Lutetium',
        'atomic number': 71,
        'electronic configuration': '(Xe) 4f^14 5d^1 6s^2',
        'atomic weight': 174.9668,
        'oxidation state': '+3',
        'melting point': 1656,
        'boiling point': 3315,
        'density': 9.84,
        'electronegativity': 1.2,
        'classification': ('solid', 'primordial'),
        'group': 'Lanthanides'
    },
    'Ac': {
        'name': 'Actinium',
        'atomic number': 89,
        'electronic configuration': '(Rn) 6d^1 7s^2',
        'atomic weight': 227,
        'oxidation state': '+3',
        'melting point': 1050,
        'boiling point': 320,
        'density': None,
        'electronegativity': 1.1,
        'classification': ('solid', 'rise naturally from decay',
                           'radio active'),
        'group': 'Actinides'
    },
    'Th': {
        'name': 'Thorium',
        'atomic number': 90,
        'electronic configuration': '(Rn) 5f^0 6d^2 7s^2',
        'atomic weight': 90,
        'oxidation state': '+4',
        'melting point': 1750,
        'boiling point': 4790,
        'density': 11.0,
        'electronegativity': 1.3,
        'classification': ('solid', 'primordial', 'radio active'),
        'group': 'Actinides'
    },
    'Pa': {
        'name': 'Protactinium',
        'atomic number': 91,
        'electronic configuration': '(Rn) 5f^2 6d^1 7s^2',
        'atomic weight': 231.04,
        'oxidation state': '+4, 5',
        'melting point': 1600,
        'boiling point': None,
        'density': None,
        'electronegativity': 1.5,
        'classification': ('solid', 'rise naturally from decay',
                           'radio active'),
        'group': 'Actinides'
    },
    'U': {
        'name': 'Uranium',
        'atomic number': 92,
        'electronic configuration': '(Rn) 5f^3 6d^1 7s^2',
        'atomic weight': 238.03,
        'oxidation state': '+3, 4, 5, 6',
        'melting point': 1132,
        'boiling point': 3818,
        'density': 19.05,
        'electronegativity': 1.7,
        'classification': ('solid', 'primordial', 'radio active'),
        'group': 'Actinides'
    },
    'Np': {
        'name': 'Neptunium',
        'atomic number': 93,
        'electronic configuration': '(Rn) 5f^4 6d^1 7s^2',
        'atomic weight': 237,
        'oxidation state': '+3, 4, 5, 6',
        'melting point': 640,
        'boiling point': 3902,
        'density': None,
        'electronegativity': 1.3,
        'classification': ('solid', 'rise naturally from decay',
                           'radio active'),
        'group': 'Actinides'
    },
    'Pu': {
        'name': 'Plutonium',
        'atomic number': 94,
        'electronic configuration': '(Rn) 5f^8 6d^0 7s^2',
        'atomic weight': 244,
        'oxidation state': '+3, 4, 5, 6',
        'melting point': 641,
        'boiling point': 3232,
        'density': None,
        'electronegativity': 1.3,
        'classification': ('solid', 'primordial', 'radio active'),
        'group': 'Actinides'
    },
    'Am': {
        'name': 'Americium',
        'atomic number': 95,
        'electronic configuration': '(Rn) 5f^7 6d^0 7s^2',
        'atomic weight': 243,
        'oxidation state': '+3, 4, 5, 6',
        'melting point': 994,
        'boiling point': 2607,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Actinides'
    },
    'Cm': {
        'name': 'Curium',
        'atomic number': 96,
        'electronic configuration': '(Rn) 5f^7 6d^1 7s^2',
        'atomic weight': 247,
        'oxidation state': '+3',
        'melting point': 1340,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Actinides'
    },
    'Bk': {
        'name': 'Berkelium',
        'atomic number': 97,
        'electronic configuration': '(Rn) 5f^9 6d^0 7s^2',
        'atomic weight': 247,
        'oxidation state': '+3, 4',
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Actinides'
    },
    'Cf': {
        'name': 'Californium',
        'atomic number': 98,
        'electronic configuration': '(Rn) 5f^10 6d^0 7s^2',
        'atomic weight': 251,
        'oxidation state': '+3',
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Actinides'
    },
    'Es': {
        'name': 'Einsteinium',
        'atomic number': 99,
        'electronic configuration': '(Rn) 5f^11 6d^0 7s^2',
        'atomic weight': 252,
        'oxidation state': '+3',
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Actinides'
    },
    'Fm': {
        'name': 'Fermium',
        'atomic number': 100,
        'electronic configuration': '(Rn) 5f^12 6d^0 7s^2',
        'atomic weight': 257,
        'oxidation state': '+3',
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Actinides'
    },
    'Md': {
        'name': 'Mendelevium',
        'atomic number': 101,
        'electronic configuration': '(Rn) 5f^13 6d^0 7s^2',
        'atomic weight': 258,
        'oxidation state': '+2, 3',
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Actinides'
    },
    'No': {
        'name': 'Nobelium',
        'atomic number': 102,
        'electronic configuration': '(Rn) 5f^14 6d^0 7s^2',
        'atomic weight': 259,
        'oxidation state': '+2, 3',
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Actinides'
    },
    'Lr': {
        'name': 'Lawrencium',
        'atomic number': 103,
        'electronic configuration': '(Rn) 5f^14 6d^1 7s^2',
        'atomic weight': 262,
        'oxidation state': '+3',
        'melting point': None,
        'boiling point': None,
        'density': None,
        'electronegativity': None,
        'classification': ('solid', 'synthetic', 'radio active'),
        'group': 'Actinides'
    }
}

SORTED_TABLE_BY_ATOMIC_NUMBER = {}
for i in range(1, len(TABLE)+1):
    _element = find_element_by_atomic_number(i)
    if _element is not None:
        SORTED_TABLE_BY_ATOMIC_NUMBER[_element['symbol']] = _element

GROUPS = {}
for element in TABLE:
    if TABLE[element]['group'] not in GROUPS:
        GROUPS[TABLE[element]['group']] = []
    GROUPS[TABLE[element]['group']].append(
        f"{TABLE[element]['name']} {element}")


if __name__ == '__main__':
    for g, e in GROUPS.items():
        print(g.upper())
        for element in e:
            print('\t', element)
            for k, v in TABLE[element.split()[1]].items():
                print('\t\t', k+':', v)
        print()
    for i, d in SORTED_TABLE_BY_ATOMIC_NUMBER.items():
        print(d['atomic number'], i, d['name'])
    print(find_element_by_atomic_number(5))
